language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install -r openstack_gerrit/requirements.txt
# command to run tests
script:
  - make test
  - make lint

notifications:
  slack: ibmcapstone:jNa6gRvxjCSuuagomzZ94EQX
  email: false
